version: "3.5"
services:
  php:
    container_name: ${COMPOSE_PROJECT_NAME}_php
    build:
      context: ./docker/php
      args:
        - UID
        - USER_NAME
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    user: ${USER_NAME}
    depends_on:
      - mysql
      - rabbitmq
    expose:
      - 9000
    environment:
      PHP_IDE_CONFIG: "serverName=symfony_example"
      MESSENGER_TRANSPORT_DSN: ${MESSENGER_TRANSPORT_DSN}
      DATABASE_URL: ${DATABASE_URL}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      internal:
  nginx:
    image: nginx:latest
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html:ro
    depends_on:
      - php
    networks:
      - internal
  mysql:
    image: mysql:8.0
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=symfony
    ports:
      - "3306:3306"
    networks:
      - internal
  rabbitmq:
    image: rabbitmq:3.8.7-management
    container_name: ${COMPOSE_PROJECT_NAME}_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - internal
  redis:
    image: redis:4.0.9
    container_name: ${COMPOSE_PROJECT_NAME}_redis
    ports:
      - "6379:6379"
    networks:
      internal:
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: ${COMPOSE_PROJECT_NAME}_kafka
    networks:
      internal:
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
  kafka-ui:
    container_name: ${COMPOSE_PROJECT_NAME}_kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: wizard_test
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      internal:
networks:
  internal:

