version: "3.5"
services:
  php:
    container_name: ${COMPOSE_PROJECT_NAME}_php
    build:
      context: ./docker/php
      args:
        - UID
        - USER_NAME
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    user: ${USER_NAME}
    depends_on:
      - mysql
      - rabbitmq
    expose:
      - 9000
    environment:
      PHP_IDE_CONFIG: "serverName=symfony_example"
      MESSENGER_TRANSPORT_DSN: ${MESSENGER_TRANSPORT_DSN}
      DATABASE_URL: ${DATABASE_URL}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      internal:
  nginx:
    image: nginx:latest
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    build:
      context: ./
      args:
        - "BUILD_ARGUMENT_ENV=dev"
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html:ro
    depends_on:
      - php
    networks:
      - internal
  mysql:
    image: mysql:8.0
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=symfony
    ports:
      - "3306:3306"
    networks:
      - internal
  rabbitmq:
    image: rabbitmq:3.8.7-management
    container_name: ${COMPOSE_PROJECT_NAME}_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - internal
  redis:
    image: redis:4.0.9
    container_name: ${COMPOSE_PROJECT_NAME}_redis
    ports:
      - "6379:6379"
    networks:
      internal:
networks:
  internal:

