framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'
            rabbit_transport:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 1
                    delay: 1000
                    multiplier: 1
                    max_delay: 0
                options:
                    exchange:
                        name: high
                    queues:
                        messages_high: ~
            kafka_transport:
                dsn: '%env(KAFKA_URL)%'
                failure_transport: failed
                retry_strategy:
                    max_retries: 0
                # serializer: App\Infrastructure\Messenger\MySerializer
                options:
                    flushTimeout: 10000
                    flushRetries: 5
                    topic:
                        name: 'eventsTopic'
                    commitAsync: true
                    receiveTimeout: 10000
                    topic_conf:
                        auto.offset.reset: 'earliest'
                    kafka_conf:
                        enable.auto.offset.store: 'false'
                        group.id: 'my-group-id' # should be unique per consumer
        routing:
            App\Messenger\Message\Message: kafka_transport

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
